dbt_:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: warehouse
      pass: warehouse
      dbname: warehouse
      schema: warehouse

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev
